export const channels = {
  appearanceSetThemeSource: "appearance:set-theme-source",
  brandingGet: "branding:get",
  runtimeGet: "runtime:get",
  runtimeRestart: "runtime:restart",
  runtimePendingRestart: "runtime:pending-restart",
  runtimeDecideRestart: "runtime:decide-restart",
  runtimeRestartRequested: "runtime:restart-requested",
  runtimeRestartRecovery: "runtime:restart-recovery",
  runtimeAcknowledgeRestartRecovery: "runtime:acknowledge-restart-recovery",
  runtimeClientReady: "runtime:client-ready",
  runtimeStatus: "runtime:status",
  telemetryScreen: "telemetry:screen",
  updatesGet: "updates:get",
  updatesDownload: "updates:download",
  updatesInstall: "updates:install",
  updatesStatus: "updates:status",
} as const;
