import { createHash } from 'node:crypto'
import type { BrowserTab, BrowserTool } from './native-contract.js'

export function webmcpCallError(code: string, message: string, recovery: string, execution: 'not_dispatched' | 'unknown' = 'not_dispatched'): Error {
  return new Error(JSON.stringify({ code, execution, message, recovery }))
}

export interface BoundWebMCPTool {
  callName: string
  tool: BrowserTool
  tabId: string
  documentId: string
  fingerprint: string
}

function canonical(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(canonical)
  if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => [key, canonical(item)]))
  return value
}
const json = (value: unknown) => JSON.stringify(canonical(value))
const fingerprint = (tab: BrowserTab, tool: BrowserTool) => json([tab.id, tab.documentId, tool])
const hash = (value: string) => createHash('sha256').update(value).digest('hex').slice(0, 20)

/** Stable public schemas and separately frozen, request-scoped execution targets. */
export class WebMCPBindings {
  private request = new Map<string, BoundWebMCPTool>()

  clear() { this.request.clear() }

  /** Observation never retargets calls already generated by the model. */
  discover(tab: BrowserTab | undefined): BoundWebMCPTool[] {
    const groups = new Map<string, Map<string, BrowserTool>>()
    for (const tool of tab && !tab.loading ? tab.tools : []) {
      // Random document/frame/revision IDs belong to the host, not the model's schema.
      const semantic = json([tool.source, tool.name, tool.description, tool.inputSchema])
      const group = groups.get(semantic) ?? new Map<string, BrowserTool>()
      group.set(fingerprint(tab!, tool), tool)
      groups.set(semantic, group)
    }
    const entries: BoundWebMCPTool[] = []
    for (const [semantic, group] of groups) {
      for (const [identity, tool] of group) {
        // Duplicate capabilities in distinct frames must remain distinguishable.
        const discriminator = group.size === 1 ? semantic : json([semantic, tool.origin, tool.frameId])
        const slug = tool.name.replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 30) || 'tool'
        entries.push({ callName: `webmcp__${slug}__${hash(discriminator)}`, tool: canonical(tool) as BrowserTool, tabId: tab!.id, documentId: tab!.documentId, fingerprint: identity })
      }
    }
    return entries.sort((a, b) => a.callName.localeCompare(b.callName))
  }

  /** Only the model-step boundary may replace a running request's targets. */
  commit(entries: BoundWebMCPTool[]) {
    this.request = new Map(entries.map(entry => [entry.callName, structuredClone(entry)]))
  }

  resolve(callName: string, tab: BrowserTab): BrowserTool {
    const entry = this.request.get(callName)
    const current = entry && tab.tools.find(tool => tool.name === entry.tool.name && tool.frameId === entry.tool.frameId)
    if (!entry || tab.loading || tab.id !== entry.tabId || tab.documentId !== entry.documentId
      || !current || fingerprint(tab, current) !== entry.fingerprint) {
      this.request.delete(callName)
      throw webmcpCallError('stale_webmcp_tool', 'This tool is unavailable on the page captured for this model request, or the page changed.', 'Inspect current page/business state. The next model request refreshes its page bindings. No action was dispatched.')
    }
    return entry.tool
  }
}
